In [1]:
# Import Dependencies
import pandas as pd
import numpy as np
from datetime import datetime

# Read the CSV into a Pandas DataFrame
intake_csv = "Resources/Austin_Animal_Center_Intakes.csv"
outcome_csv= "Resources/Austin_Animal_Center_Outcomes.csv"

# Read the CSV into a Pandas DataFrame and convert to datetime64

intake_df = pd.read_csv(intake_csv, index_col='Animal ID', parse_dates=["DateTime", "MonthYear"])
outcome_df = pd.read_csv(outcome_csv, index_col='Animal ID', parse_dates=["DateTime", "MonthYear"])

#update intake file with column reflecting number of intakes
#and select outcomes for animals with 1 or 2 intakes
intake_counts=intake_df.groupby(['Animal ID']).size().reset_index(name='counts')
intake_df=pd.merge(intake_df, intake_counts, on="Animal ID", how="outer")
reduced_intake_df=intake_df.query('counts <3')

#update outtake file with column reflecting number of intakes per animal
#and select outcomes for animals with 1 or 2 intakes
outcome_df=pd.merge(outcome_df, intake_counts, on="Animal ID", how="left")
reduced_outcome_df=outcome_df.query('counts <3')
#reduced_outcome_df=reduced_outcome_df.drop(columns=['counts'])

In [2]:
outcome_df

,Animal ID,Name,DateTime,MonthYear,Date of Birth,Outcome Type,Outcome Subtype,Animal Type,Sex upon Outcome,Age upon Outcome,Breed,Color,counts
0,A741715,*Pebbles,2017-01-11 18:17:00,2017-01-11 18:17:00,03/07/2016,Adoption,NaN,Cat,Spayed Female,10 months,Domestic Shorthair Mix,Calico,1.0
1,A658751,Benji,2016-11-13 13:38:00,2016-11-13 13:38:00,07/14/2011,Return to Owner,NaN,Dog,Neutered Male,5 years,Border Terrier Mix,Tan,2.0
2,A721285,NaN,2016-02-24 14:42:00,2016-02-24 14:42:00,02/24/2014,Euthanasia,Suffering,Other,Unknown,2 years,Raccoon Mix,Black/Gray,1.0
3,A707443,NaN,2015-07-13 13:50:00,2015-07-13 13:50:00,06/21/2015,Transfer,Partner,Cat,Intact Female,3 weeks,Domestic Longhair Mix,Black Smoke,1.0
4,A684346,NaN,2014-07-22 16:04:00,2014-07-22 16:04:00,07/07/2014,Transfer,Partner,Cat,Intact Male,2 weeks,Domestic Shorthair Mix,Orange Tabby,1.0
5,A666430,Lucy,2013-11-07 11:47:00,2013-11-07 11:47:00,11/06/2012,Transfer,Partner,Dog,Spayed Female,1 year,Beagle Mix,White/Brown,1.0
6,A675708,*Johnny,2014-06-03 14:20:00,2014-06-03 14:20:00,03/31/2013,Adoption,NaN,Dog,Neutered Male,1 year,Pit Bull,Blue/White,1.0
7,A680386,Monday,2014-06-15 15:50:00,2014-06-15 15:50:00,06/02/2005,Transfer,Partner,Dog,Neutered Male,9 years,Miniature Schnauzer Mix,White,1.0
8,A683115,NaN,2014-07-07 14:04:00,2014-07-07 14:04:00,01/07/2014,Euthanasia,Rabies Risk,Other,Unknown,5 months,Bat Mix,Brown,1.0
9,A713785,NaN,2015-10-19 14:55:00,2015-10-19 14:55:00,05/29/2015,Transfer,Partner,Dog,Neutered Male,4 months,Labrador Retriever Mix,Red,1.0
10,A664462,*Edgar,2013-10-07 13:06:00,2013-10-07 13:06:00,06/03/2013,Transfer,Partner,Dog,Intact Male,4 months,Leonberger Mix,Brown/White,1.0
11,A741783,NaN,2017-01-12 17:02:00,2017-01-12 17:02:00,11/18/2016,Adoption,NaN,Dog,Spayed Female,1 month,Labrador Retriever Mix,Tan/White,1.0
12,A697000,Boone,2015-02-16 13:24:00,2015-02-16 13:24:00,02/16/2009,Return to Owner,NaN,Dog,Neutered Male,6 years,English Springer Spaniel Mix,Liver/White,1.0
13,A697055,Megatron,2015-02-17 15:06:00,2015-02-17 15:06:00,02/17/2012,Adoption,NaN,Dog,Spayed Female,3 years,Dachshund/Chihuahua Shorthair,Red,1.0
14,A646449,Ruby,2015-07-23 18:31:00,2015-07-23 18:31:00,01/23/2012,Return to Owner,NaN,Dog,Spayed Female,3 years,Catahoula/Labrador Retriever,Brown Brindle,1.0
15,A724228,NaN,2016-05-28 16:40:00,2016-05-28 16:40:00,03/07/2016,Adoption,Foster,Cat,Spayed Female,2 months,Domestic Shorthair Mix,Blue Tabby,1.0
16,A708122,NaN,2015-07-27 14:21:00,2015-07-27 14:21:00,07/23/2005,Transfer,Partner,Dog,Neutered Male,10 years,Pug,Fawn/Black,1.0
17,A740957,Gio,2016-12-27 10:40:00,2016-12-27 10:40:00,12/26/2015,Return to Owner,NaN,Dog,Intact Male,1 year,Chihuahua Shorthair Mix,Red/Tan,2.0
18,A710320,Yoshi,2015-09-01 16:36:00,2015-09-01 16:36:00,01/21/2010,Return to Owner,NaN,Dog,Spayed Female,5 years,Pit Bull Mix,Blue/White,1.0
19,A693700,NaN,2014-12-13 12:20:00,2014-12-13 12:20:00,12/13/2013,Euthanasia,Suffering,Other,Unknown,1 year,Squirrel Mix,Tan,1.0
20,A698683,Toby,2015-03-21 11:45:00,2015-03-21 11:45:00,03/16/2011,Return to Owner,NaN,Dog,Neutered Male,4 years,Chihuahua Longhair Mix,Cream,1.0
21,A692618,*Ella,2014-12-08 15:55:00,2014-12-08 15:55:00,11/23/2011,Transfer,Partner,Dog,Spayed Female,3 years,Chihuahua Shorthair Mix,Brown,1.0
22,A695532,Charlie,2015-01-17 17:22:00,2015-01-17 17:22:00,01/17/2013,Return to Owner,NaN,Dog,Neutered Male,2 years,Treeing Walker Coonhound Mix,White/Brown,1.0
23,A735677,NaN,2016-09-28 13:49:00,2016-09-28 13:49:00,09/06/2016,Transfer,Partner,Cat,Intact Male,3 weeks,Domestic Shorthair Mix,Brown Tabby,1.0
24,A700969,NaN,2015-04-22 08:39:00,2015-04-22 08:39:00,10/21/2014,Euthanasia,Rabies Risk,Other,Unknown,6 months,Bat,Brown,1.0
25,A720498,*Valentino,2016-02-16 00:00:00,2016-02-16 00:00:00,02/10/2014,Transfer,Partner,Dog,Neutered Male,2 years,Pug/Border Terrier,Black/Tan,1.0
26,A685067,Lucy,2014-08-14 18:45:00,2014-08-14 18:45:00,06/16/2014,Adoption,NaN,Cat,Intact Female,1 month,Domestic Shorthair Mix,Blue Tabby/White,1.0
27,A678580,*Frida,2014-06-29 17:45:00,2014-06-29 17:45:00,03/26/2014,Adoption,Offsite,Cat,Spayed Female,3 months,Domestic Shorthair Mix,White/Black,1.0
28,A675405,Stella Luna,2014-03-28 14:55:00,2014-03-28 14:55:00,03/27/2013,Return to Owner,NaN,Cat,Spayed Female,1 year,Domestic Medium Hair Mix,Black/White,1.0
29,A706392,*Ozzy,2015-11-24 11:58:00,2015-11-24 11:58:00,05/28/2015,Adoption,Foster,Cat,Neutered Male,5 months,Domestic Medium Hair Mix,Blue Tabby/White,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
87882,A778732,Mika,2018-08-23 16:34:00,2018-08-23 16:34:00,06/08/2018,Adoption,NaN,Dog,Spayed Female,2 months,Australian Cattle Dog Mix,White/Black,1.0
87883,A778449,Jaxx,2018-08-23 16:04:00,2018-08-23 16:04:00,08/15/2017,Adoption,NaN,Dog,Neutered Male,1 year,Basenji/Rhod Ridgeback,Red/White,1.0
87884,A778891,Sampson,2018-08-23 16:38:00,2018-08-23 16:38:00,06/30/2018,Adoption,NaN,Dog,Neutered Male,1 month,Chihuahua Shorthair Mix,Cream,1.0
87885,A777633,*Curie,2018-08-23 16:51:00,2018-08-23 16:51:00,04/16/2018,Adoption,NaN,Cat,Spayed Female,4 months,Domestic Shorthair Mix,Blue,1.0
87886,A769119,Phantom,2018-04-08 17:46:00,2018-04-08 17:46:00,10/30/2017,Adoption,NaN,Dog,Neutered Male,5 months,Australian Kelpie Mix,Tricolor,3.0
87887,A778210,Lulu,2018-08-23 16:19:00,2018-08-23 16:19:00,12/23/2017,Return to Owner,NaN,Dog,Spayed Female,7 months,Yorkshire Terrier Mix,Brown,1.0
87888,A769119,Phantom,2018-08-21 15:59:00,2018-08-21 15:59:00,10/30/2017,Adoption,NaN,Dog,Neutered Male,9 months,Australian Kelpie Mix,Tricolor,3.0
87889,A778698,NaN,2018-08-23 17:52:00,2018-08-23 17:52:00,02/19/2018,Adoption,NaN,Dog,Spayed Female,6 months,Blue Lacy Mix,Blue/White,1.0
87890,A778629,*Shadow,2018-08-23 17:21:00,2018-08-23 17:21:00,11/17/2017,Adoption,NaN,Dog,Spayed Female,9 months,Australian Cattle Dog Mix,Black/White,1.0
87891,A778729,Maya,2018-08-23 17:04:00,2018-08-23 17:04:00,06/08/2018,Adoption,NaN,Dog,Spayed Female,2 months,Labrador Retriever Mix,Black/White,1.0
87892,A778347,Hunzi,2018-08-23 17:45:00,2018-08-23 17:45:00,08/13/2015,Return to Owner,NaN,Dog,Neutered Male,3 years,Great Pyrenees,White/Fawn,1.0
87893,A778987,NaN,2018-08-23 17:54:00,2018-08-23 17:54:00,05/23/2018,Disposal,NaN,Other,Unknown,3 months,Raccoon Mix,Gray/Black,1.0
87894,A775947,Snooky,2018-08-23 17:17:00,2018-08-23 17:17:00,07/06/2013,Adoption,NaN,Cat,Spayed Female,5 years,Domestic Longhair Mix,Tortie,1.0
87895,A778727,Benji,2018-08-23 17:04:00,2018-08-23 17:04:00,06/19/2018,Adoption,NaN,Dog,Neutered Male,2 months,Labrador Retriever Mix,Brown,1.0
87896,A519102,Howie,2018-08-23 18:39:00,2018-08-23 18:39:00,09/12/2007,Return to Owner,NaN,Dog,Neutered Male,10 years,German Shepherd Mix,Brown/Black,1.0
87897,A748299,Jesus,2018-08-23 18:42:00,2018-08-23 18:42:00,05/01/2016,Return to Owner,NaN,Dog,Neutered Male,2 years,Pit Bull Mix,Brown Brindle/White,2.0
87898,A760947,Jezebel,2018-08-23 18:43:00,2018-08-23 18:43:00,12/26/2016,Return to Owner,NaN,Dog,Spayed Female,1 year,Staffordshire Mix,Blue/White,2.0
87899,A748299,Jesus,2017-05-08 18:43:00,2017-05-08 18:43:00,05/01/2016,Adoption,NaN,Dog,Neutered Male,1 year,Pit Bull Mix,Brown Brindle/White,2.0
87900,A778453,Chance,2018-08-23 18:39:00,2018-08-23 18:39:00,08/15/2016,Return to Owner,NaN,Dog,Neutered Male,2 years,Pit Bull Mix,Tan/White,1.0
87901,A778938,Snowball,2018-08-23 18:28:00,2018-08-23 18:28:00,08/22/2011,Return to Owner,NaN,Cat,Spayed Female,7 years,Domestic Shorthair Mix,White/Black,1.0
87902,A778730,NaN,2018-08-23 18:42:00,2018-08-23 18:42:00,06/19/2018,Adoption,NaN,Dog,Spayed Female,2 months,Labrador Retriever Mix,Black/White,1.0
87903,A778456,Be,2018-08-23 18:39:00,2018-08-23 18:39:00,08/15/2012,Return to Owner,NaN,Dog,Neutered Male,6 years,Pit Bull Mix,Brown/White,1.0
87904,A778619,*Harvey,2018-08-23 18:23:00,2018-08-23 18:23:00,06/02/2018,Adoption,NaN,Cat,Neutered Male,2 months,Domestic Shorthair Mix,Orange Tabby,1.0
87905,A778772,Taurus,2018-08-23 18:54:00,2018-08-23 18:54:00,04/20/2018,Adoption,NaN,Cat,Neutered Male,4 months,Domestic Medium Hair Mix,Orange Tabby/White,1.0
87906,A760947,Jezebel,2017-11-01 17:15:00,2017-11-01 17:15:00,12/26/2016,Adoption,NaN,Dog,Spayed Female,10 months,Staffordshire Mix,Blue/White,2.0
87907,A778542,*Periscope,2018-08-23 18:11:00,2018-08-23 18:11:00,08/16/2017,Adoption,NaN,Dog,Neutered Male,1 year,Plott Hound Mix,Black/White,1.0
87908,A773866,*Nitro,2018-08-23 18:05:00,2018-08-23 18:05:00,06/06/2016,Adoption,NaN,Dog,Neutered Male,2 years,Pit Bull Mix,Black/White,3.0
87909,A777321,Lucky Charm,2018-08-23 19:00:00,2018-08-23 19:00:00,06/12/2018,Adoption,NaN,Cat,Neutered Male,2 months,Domestic Shorthair Mix,Orange Tabby,1.0
87910,A778348,*Magnolia,2018-08-23 19:10:00,2018-08-23 19:10:00,08/13/2017,Adoption,NaN,Dog,Spayed Female,1 year,Pit Bull Mix,Blue/White,1.0
87911,A778625,Ruth,2018-08-23 19:04:00,2018-08-23 19:04:00,08/17/2017,Adoption,NaN,Dog,Spayed Female,1 year,Pointer Mix,Brown Brindle/White,1.0

In [3]:
reduced_outcome_df

,Animal ID,Name,DateTime,MonthYear,Date of Birth,Outcome Type,Outcome Subtype,Animal Type,Sex upon Outcome,Age upon Outcome,Breed,Color,counts
0,A741715,*Pebbles,2017-01-11 18:17:00,2017-01-11 18:17:00,03/07/2016,Adoption,NaN,Cat,Spayed Female,10 months,Domestic Shorthair Mix,Calico,1.0
1,A658751,Benji,2016-11-13 13:38:00,2016-11-13 13:38:00,07/14/2011,Return to Owner,NaN,Dog,Neutered Male,5 years,Border Terrier Mix,Tan,2.0
2,A721285,NaN,2016-02-24 14:42:00,2016-02-24 14:42:00,02/24/2014,Euthanasia,Suffering,Other,Unknown,2 years,Raccoon Mix,Black/Gray,1.0
3,A707443,NaN,2015-07-13 13:50:00,2015-07-13 13:50:00,06/21/2015,Transfer,Partner,Cat,Intact Female,3 weeks,Domestic Longhair Mix,Black Smoke,1.0
4,A684346,NaN,2014-07-22 16:04:00,2014-07-22 16:04:00,07/07/2014,Transfer,Partner,Cat,Intact Male,2 weeks,Domestic Shorthair Mix,Orange Tabby,1.0
5,A666430,Lucy,2013-11-07 11:47:00,2013-11-07 11:47:00,11/06/2012,Transfer,Partner,Dog,Spayed Female,1 year,Beagle Mix,White/Brown,1.0
6,A675708,*Johnny,2014-06-03 14:20:00,2014-06-03 14:20:00,03/31/2013,Adoption,NaN,Dog,Neutered Male,1 year,Pit Bull,Blue/White,1.0
7,A680386,Monday,2014-06-15 15:50:00,2014-06-15 15:50:00,06/02/2005,Transfer,Partner,Dog,Neutered Male,9 years,Miniature Schnauzer Mix,White,1.0
8,A683115,NaN,2014-07-07 14:04:00,2014-07-07 14:04:00,01/07/2014,Euthanasia,Rabies Risk,Other,Unknown,5 months,Bat Mix,Brown,1.0
9,A713785,NaN,2015-10-19 14:55:00,2015-10-19 14:55:00,05/29/2015,Transfer,Partner,Dog,Neutered Male,4 months,Labrador Retriever Mix,Red,1.0
10,A664462,*Edgar,2013-10-07 13:06:00,2013-10-07 13:06:00,06/03/2013,Transfer,Partner,Dog,Intact Male,4 months,Leonberger Mix,Brown/White,1.0
11,A741783,NaN,2017-01-12 17:02:00,2017-01-12 17:02:00,11/18/2016,Adoption,NaN,Dog,Spayed Female,1 month,Labrador Retriever Mix,Tan/White,1.0
12,A697000,Boone,2015-02-16 13:24:00,2015-02-16 13:24:00,02/16/2009,Return to Owner,NaN,Dog,Neutered Male,6 years,English Springer Spaniel Mix,Liver/White,1.0
13,A697055,Megatron,2015-02-17 15:06:00,2015-02-17 15:06:00,02/17/2012,Adoption,NaN,Dog,Spayed Female,3 years,Dachshund/Chihuahua Shorthair,Red,1.0
14,A646449,Ruby,2015-07-23 18:31:00,2015-07-23 18:31:00,01/23/2012,Return to Owner,NaN,Dog,Spayed Female,3 years,Catahoula/Labrador Retriever,Brown Brindle,1.0
15,A724228,NaN,2016-05-28 16:40:00,2016-05-28 16:40:00,03/07/2016,Adoption,Foster,Cat,Spayed Female,2 months,Domestic Shorthair Mix,Blue Tabby,1.0
16,A708122,NaN,2015-07-27 14:21:00,2015-07-27 14:21:00,07/23/2005,Transfer,Partner,Dog,Neutered Male,10 years,Pug,Fawn/Black,1.0
17,A740957,Gio,2016-12-27 10:40:00,2016-12-27 10:40:00,12/26/2015,Return to Owner,NaN,Dog,Intact Male,1 year,Chihuahua Shorthair Mix,Red/Tan,2.0
18,A710320,Yoshi,2015-09-01 16:36:00,2015-09-01 16:36:00,01/21/2010,Return to Owner,NaN,Dog,Spayed Female,5 years,Pit Bull Mix,Blue/White,1.0
19,A693700,NaN,2014-12-13 12:20:00,2014-12-13 12:20:00,12/13/2013,Euthanasia,Suffering,Other,Unknown,1 year,Squirrel Mix,Tan,1.0
20,A698683,Toby,2015-03-21 11:45:00,2015-03-21 11:45:00,03/16/2011,Return to Owner,NaN,Dog,Neutered Male,4 years,Chihuahua Longhair Mix,Cream,1.0
21,A692618,*Ella,2014-12-08 15:55:00,2014-12-08 15:55:00,11/23/2011,Transfer,Partner,Dog,Spayed Female,3 years,Chihuahua Shorthair Mix,Brown,1.0
22,A695532,Charlie,2015-01-17 17:22:00,2015-01-17 17:22:00,01/17/2013,Return to Owner,NaN,Dog,Neutered Male,2 years,Treeing Walker Coonhound Mix,White/Brown,1.0
23,A735677,NaN,2016-09-28 13:49:00,2016-09-28 13:49:00,09/06/2016,Transfer,Partner,Cat,Intact Male,3 weeks,Domestic Shorthair Mix,Brown Tabby,1.0
24,A700969,NaN,2015-04-22 08:39:00,2015-04-22 08:39:00,10/21/2014,Euthanasia,Rabies Risk,Other,Unknown,6 months,Bat,Brown,1.0
25,A720498,*Valentino,2016-02-16 00:00:00,2016-02-16 00:00:00,02/10/2014,Transfer,Partner,Dog,Neutered Male,2 years,Pug/Border Terrier,Black/Tan,1.0
26,A685067,Lucy,2014-08-14 18:45:00,2014-08-14 18:45:00,06/16/2014,Adoption,NaN,Cat,Intact Female,1 month,Domestic Shorthair Mix,Blue Tabby/White,1.0
27,A678580,*Frida,2014-06-29 17:45:00,2014-06-29 17:45:00,03/26/2014,Adoption,Offsite,Cat,Spayed Female,3 months,Domestic Shorthair Mix,White/Black,1.0
28,A675405,Stella Luna,2014-03-28 14:55:00,2014-03-28 14:55:00,03/27/2013,Return to Owner,NaN,Cat,Spayed Female,1 year,Domestic Medium Hair Mix,Black/White,1.0
29,A706392,*Ozzy,2015-11-24 11:58:00,2015-11-24 11:58:00,05/28/2015,Adoption,Foster,Cat,Neutered Male,5 months,Domestic Medium Hair Mix,Blue Tabby/White,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
87879,A778703,NaN,2018-08-23 16:30:00,2018-08-23 16:30:00,04/19/2018,Adoption,NaN,Cat,Neutered Male,4 months,Domestic Shorthair Mix,Orange Tabby/White,1.0
87880,A777217,Tank,2018-08-23 16:17:00,2018-08-23 16:17:00,07/25/2016,Adoption,NaN,Dog,Neutered Male,2 years,American Staffordshire Terrier Mix,Black/White,1.0
87881,A777285,Romeo,2018-08-23 16:32:00,2018-08-23 16:32:00,07/26/2016,Adoption,NaN,Dog,Neutered Male,2 years,Chihuahua Shorthair Mix,Brown,1.0
87882,A778732,Mika,2018-08-23 16:34:00,2018-08-23 16:34:00,06/08/2018,Adoption,NaN,Dog,Spayed Female,2 months,Australian Cattle Dog Mix,White/Black,1.0
87883,A778449,Jaxx,2018-08-23 16:04:00,2018-08-23 16:04:00,08/15/2017,Adoption,NaN,Dog,Neutered Male,1 year,Basenji/Rhod Ridgeback,Red/White,1.0
87884,A778891,Sampson,2018-08-23 16:38:00,2018-08-23 16:38:00,06/30/2018,Adoption,NaN,Dog,Neutered Male,1 month,Chihuahua Shorthair Mix,Cream,1.0
87885,A777633,*Curie,2018-08-23 16:51:00,2018-08-23 16:51:00,04/16/2018,Adoption,NaN,Cat,Spayed Female,4 months,Domestic Shorthair Mix,Blue,1.0
87887,A778210,Lulu,2018-08-23 16:19:00,2018-08-23 16:19:00,12/23/2017,Return to Owner,NaN,Dog,Spayed Female,7 months,Yorkshire Terrier Mix,Brown,1.0
87889,A778698,NaN,2018-08-23 17:52:00,2018-08-23 17:52:00,02/19/2018,Adoption,NaN,Dog,Spayed Female,6 months,Blue Lacy Mix,Blue/White,1.0
87890,A778629,*Shadow,2018-08-23 17:21:00,2018-08-23 17:21:00,11/17/2017,Adoption,NaN,Dog,Spayed Female,9 months,Australian Cattle Dog Mix,Black/White,1.0
87891,A778729,Maya,2018-08-23 17:04:00,2018-08-23 17:04:00,06/08/2018,Adoption,NaN,Dog,Spayed Female,2 months,Labrador Retriever Mix,Black/White,1.0
87892,A778347,Hunzi,2018-08-23 17:45:00,2018-08-23 17:45:00,08/13/2015,Return to Owner,NaN,Dog,Neutered Male,3 years,Great Pyrenees,White/Fawn,1.0
87893,A778987,NaN,2018-08-23 17:54:00,2018-08-23 17:54:00,05/23/2018,Disposal,NaN,Other,Unknown,3 months,Raccoon Mix,Gray/Black,1.0
87894,A775947,Snooky,2018-08-23 17:17:00,2018-08-23 17:17:00,07/06/2013,Adoption,NaN,Cat,Spayed Female,5 years,Domestic Longhair Mix,Tortie,1.0
87895,A778727,Benji,2018-08-23 17:04:00,2018-08-23 17:04:00,06/19/2018,Adoption,NaN,Dog,Neutered Male,2 months,Labrador Retriever Mix,Brown,1.0
87896,A519102,Howie,2018-08-23 18:39:00,2018-08-23 18:39:00,09/12/2007,Return to Owner,NaN,Dog,Neutered Male,10 years,German Shepherd Mix,Brown/Black,1.0
87897,A748299,Jesus,2018-08-23 18:42:00,2018-08-23 18:42:00,05/01/2016,Return to Owner,NaN,Dog,Neutered Male,2 years,Pit Bull Mix,Brown Brindle/White,2.0
87898,A760947,Jezebel,2018-08-23 18:43:00,2018-08-23 18:43:00,12/26/2016,Return to Owner,NaN,Dog,Spayed Female,1 year,Staffordshire Mix,Blue/White,2.0
87899,A748299,Jesus,2017-05-08 18:43:00,2017-05-08 18:43:00,05/01/2016,Adoption,NaN,Dog,Neutered Male,1 year,Pit Bull Mix,Brown Brindle/White,2.0
87900,A778453,Chance,2018-08-23 18:39:00,2018-08-23 18:39:00,08/15/2016,Return to Owner,NaN,Dog,Neutered Male,2 years,Pit Bull Mix,Tan/White,1.0
87901,A778938,Snowball,2018-08-23 18:28:00,2018-08-23 18:28:00,08/22/2011,Return to Owner,NaN,Cat,Spayed Female,7 years,Domestic Shorthair Mix,White/Black,1.0
87902,A778730,NaN,2018-08-23 18:42:00,2018-08-23 18:42:00,06/19/2018,Adoption,NaN,Dog,Spayed Female,2 months,Labrador Retriever Mix,Black/White,1.0
87903,A778456,Be,2018-08-23 18:39:00,2018-08-23 18:39:00,08/15/2012,Return to Owner,NaN,Dog,Neutered Male,6 years,Pit Bull Mix,Brown/White,1.0
87904,A778619,*Harvey,2018-08-23 18:23:00,2018-08-23 18:23:00,06/02/2018,Adoption,NaN,Cat,Neutered Male,2 months,Domestic Shorthair Mix,Orange Tabby,1.0
87905,A778772,Taurus,2018-08-23 18:54:00,2018-08-23 18:54:00,04/20/2018,Adoption,NaN,Cat,Neutered Male,4 months,Domestic Medium Hair Mix,Orange Tabby/White,1.0
87906,A760947,Jezebel,2017-11-01 17:15:00,2017-11-01 17:15:00,12/26/2016,Adoption,NaN,Dog,Spayed Female,10 months,Staffordshire Mix,Blue/White,2.0
87907,A778542,*Periscope,2018-08-23 18:11:00,2018-08-23 18:11:00,08/16/2017,Adoption,NaN,Dog,Neutered Male,1 year,Plott Hound Mix,Black/White,1.0
87909,A777321,Lucky Charm,2018-08-23 19:00:00,2018-08-23 19:00:00,06/12/2018,Adoption,NaN,Cat,Neutered Male,2 months,Domestic Shorthair Mix,Orange Tabby,1.0
87910,A778348,*Magnolia,2018-08-23 19:10:00,2018-08-23 19:10:00,08/13/2017,Adoption,NaN,Dog,Spayed Female,1 year,Pit Bull Mix,Blue/White,1.0
87911,A778625,Ruth,2018-08-23 19:04:00,2018-08-23 19:04:00,08/17/2017,Adoption,NaN,Dog,Spayed Female,1 year,Pointer Mix,Brown Brindle/White,1.0

In [4]:
#now take single intake animals and match with any available outcome
reduced_intake_only_one_df=reduced_intake_df.query('counts <2')
#reduced_intake_only_one_df=reduced_intake_only_one_df.add_prefix('IN_')
reduced_outcome_df=reduced_outcome_df.add_prefix("OUT_")

reduced_intake_only_one_df=reduced_intake_only_one_df.rename(index=str,columns={"IN_Animal ID": "Animal ID"})
reduced_outcome_df=reduced_outcome_df.rename(index=str,columns={"OUT_Animal ID": "Animal ID"})
one_intake_merged=pd.merge(reduced_intake_only_one_df, reduced_outcome_df, on="Animal ID", how="left")

In [5]:
one_intake_merged["num_of_intakes_for_ID"]=1

In [6]:
#now take two intake animals and figure out order of intakes and outcomes
reduced_intake_two_df=reduced_intake_df.query('counts !=1')

In [7]:
reduced_intake_two_first_date_lookup_df=reduced_intake_two_df.groupby('Animal ID').aggregate(['min']).reset_index()
reduced_intake_two_first_date_lookup_df = reduced_intake_two_first_date_lookup_df[['Animal ID','DateTime']]
reduced_intake_two_first_date_lookup_df["stay_number"]=1
reduced_intake_two_first_date_lookup_df.columns = reduced_intake_two_first_date_lookup_df.columns.droplevel(1)


reduced_intake_two_first_date_lookup_df.head()

  Animal ID            DateTime  stay_number
0   A245945 2014-07-03 17:55:00            1
1   A282897 2013-11-21 13:45:00            1
2   A287017 2014-12-12 07:04:00            1
3   A304036 2015-06-06 14:34:00            1
4   A307010 2016-09-25 12:51:00            1

In [8]:
reduced_intake_two_second_date_lookup_df=reduced_intake_two_df.groupby('Animal ID').aggregate(['max']).reset_index()
reduced_intake_two_second_date_lookup_df = reduced_intake_two_second_date_lookup_df[['Animal ID','DateTime']]
reduced_intake_two_second_date_lookup_df["stay_number"]=2
reduced_intake_two_second_date_lookup_df.columns = reduced_intake_two_second_date_lookup_df.columns.droplevel(1)

In [9]:
reduced_intake_two_second_date_lookup_df.head()

  Animal ID            DateTime  stay_number
0   A245945 2015-05-20 22:34:00            2
1   A282897 2015-07-06 15:06:00            2
2   A287017 2015-08-16 12:19:00            2
3   A304036 2016-04-19 08:22:00            2
4   A307010 2017-06-01 11:47:00            2

In [10]:
multiple_intakes_order_lookup = reduced_intake_two_first_date_lookup_df.append(reduced_intake_two_second_date_lookup_df)

In [11]:
#multiple_intakes_order_lookup

In [12]:
#reduced_intake_two_df

reduced_intake_two_df=pd.merge(reduced_intake_two_df, multiple_intakes_order_lookup, on=["Animal ID","DateTime"], how="left")
#reduced_intake_two_df

In [13]:
#look at outcome records for the two-intake group and determine order

In [14]:
#reduced_outcome_df

In [ ]:

reduced_outcome_two_first_date_lookup_df=reduced_outcome_df.groupby('Animal ID').aggregate(['min']).reset_index()
reduced_outcome_two_first_date_lookup_df = reduced_outcome_two_first_date_lookup_df[['Animal ID','OUT_DateTime']]
reduced_outcome_two_first_date_lookup_df["stay_number"]=1
reduced_outcome_two_first_date_lookup_df.columns = reduced_outcome_two_first_date_lookup_df.columns.droplevel(1)


reduced_outcome_two_first_date_lookup_df.head()

In [ ]:
reduced_outcome_df=pd.merge(reduced_outcome_df, reduced_outcome_two_first_date_lookup_df, on=["Animal ID","OUT_DateTime"], how="left")

reduced_outcome_df

In [ ]:
reduced_outcome_df['stay_number']=reduced_outcome_df['stay_number'].fillna(2)
#reduced_outcome_df

In [ ]:
#reduced_intake_two_df=reduced_intake_two_df.add_prefix('IN_')
reduced_intake_two_df=reduced_intake_two_df.rename(index=str,columns={"IN_Animal ID": "Animal ID","IN_stay_number":"stay_number"})
reduced_intake_two_df

In [ ]:
#merge the multiple intake with coressponsing outcomes - will not yield two outcomes for animals still in residence
two_intakes_merged=pd.merge(reduced_intake_two_df, reduced_outcome_df, on=["Animal ID", "stay_number"], how="left")
two_intakes_merged["num_of_intakes_for_ID"]="2"

In [ ]:
two_intakes_merged

In [ ]:
one_intake_merged

In [ ]:
working_base_master=one_intake_merged.append(two_intakes_merged, ignore_index=True)

In [ ]:
working_base_master

In [ ]:
working_base_master['time_to_exit'] = working_base_master['OUT_DateTime']-working_base_master['DateTime']

In [ ]:
#working_base_master['time_to_exit']=working_base_master['time_to_exit'] / np.timedelta64(1, 'D')

In [ ]:
working_base_master['time_to_exit'].dtype

In [ ]:
working_base_master

In [ ]:
#working_base_master['time_to_exit']=pd.to_datetime(working_base_master['time_to_exit'])
working_base_master.dtypes

## Create DF with intake data for holiday analysis

In [ ]:
q4df=pd.DataFrame(working_base_master[['Animal ID', "Animal Type", "DateTime"]])
q4df.dtypes

## Convert date time column to just dates

In [ ]:
q4df["DateTime"]=q4df["DateTime"].dt.round("D")
q4df.head()

# Group data YoY based on timeframe of Thanksgiving-New Years Day with cushion on either side to understand lead time

### Each year would be separate variable to later be combined

### Display dataframe to confirm window data

In [ ]:
#pull data out for intakes between 11/1-1/14

start_date13="2013-11-20"
end_date13="2014-1-8"
Holiday_Window13 = (q4df['DateTime'] > start_date13) & (q4df['DateTime']  <= end_date13)
q4df_2013=q4df.loc[Holiday_Window13]

start_date14="2014-11-20"
end_date14="2015-1-8"
Holiday_Window14 = (q4df['DateTime'] > start_date14) & (q4df['DateTime']  <= end_date14)
q4df_2014=q4df.loc[Holiday_Window14]
q4df_2014

start_date15="2015-11-20"
end_date15="2016-1-8"
Holiday_Window15 = (q4df['DateTime'] > start_date15) & (q4df['DateTime']  <= end_date15)
q4df_2015=q4df.loc[Holiday_Window15]
q4df_2015

start_date16="2016-11-20"
end_date16="2017-1-8"
Holiday_Window16 = (q4df['DateTime'] > start_date16) & (q4df['DateTime']  <= end_date16)
q4df_2016=q4df.loc[Holiday_Window16]
q4df_2016

start_date17="2017-11-20"
end_date17="2018-1-8"
Holiday_Window17 = (q4df['DateTime'] > start_date17) & (q4df['DateTime']  <= end_date17)
q4df_2017=q4df.loc[Holiday_Window17]

q4df_2017.head()

## Confirm Data types in new Data Frames with holiday time frames

In [ ]:
q4df_2013.dtypes

## Determine occurrences of intake per day  using valuecounts of date column.

#### Then remove year from date column to later merge on month/day

In [ ]:
#This is getting the amount of occurences of the date

datecounts_2013=q4df_2013['DateTime'].value_counts()
q4df_2013dict={"Date":datecounts_2013.index,
               "2013 intakes":datecounts_2013}
new13df=pd.DataFrame(q4df_2013dict)
new13df=new13df.sort_values('Date')
new13df.head()

datecounts_2014=q4df_2014["DateTime"].value_counts()
q4df_2014dict={"Date": datecounts_2014.index,
               "2014 intakes":datecounts_2014}
new14df=pd.DataFrame(q4df_2014dict)
new14df=new14df.sort_values('Date')
new14df.head()

datecounts_2015=q4df_2015["DateTime"].value_counts()
q4df_2015dict={"Date": datecounts_2015.index,
               "2015 intakes":datecounts_2015}
new15df=pd.DataFrame(q4df_2015dict)
new15df=new15df.sort_values('Date')
new15df.head()


datecounts_2016=q4df_2016["DateTime"].value_counts()
q4df_2016dict={"Date": datecounts_2016.index,
               "2016 intakes":datecounts_2016}
new16df=pd.DataFrame(q4df_2016dict)
new16df=new16df.sort_values('Date')
new16df.head()


datecounts_2017=q4df_2017["DateTime"].value_counts()
q4df_2017dict={"Date": datecounts_2017.index,
               "2017 intakes":datecounts_2017}
new17df=pd.DataFrame.from_dict(q4df_2017dict)
new17df=new17df.sort_values('Date')


new13df['Date']=new13df['Date'].astype(str).str[5:]
new14df['Date']=new14df['Date'].astype(str).str[5:]
new15df['Date']=new15df['Date'].astype(str).str[5:]
new16df['Date']=new16df['Date'].astype(str).str[5:]
new17df['Date']=new17df['Date'].astype(str).str[5:]

new17df.head()

## Merge YoY data to one dataframe

In [ ]:
YoY_Total_Intake_Combined=pd.merge(new13df, new14df, on="Date")
YoY_Total_Intake_Combined=pd.merge(YoY_Total_Intake_Combined, new15df, on="Date")
YoY_Total_Intake_Combined=pd.merge(YoY_Total_Intake_Combined, new16df, on="Date")
YoY_Total_Intake_Combined=pd.merge(YoY_Total_Intake_Combined, new17df, on="Date")
YoY_Total_Intake_Combined.head()

## Import matplotlib for visuals

In [ ]:
import matplotlib.pyplot as plt

## Set index in combined dataframe and confirm data types

In [ ]:
#biggestdf.dtypes
YoY_Total_Intake_Combined=YoY_Total_Intake_Combined.set_index(YoY_Total_Intake_Combined['Date'])

In [ ]:
type(YoY_Total_Intake_Combined)
YoY_Total_Intake_Combined.dtypes

## Create bar chart with YoY data to compare. 

#### Use subplot function to split data into separate comparable graphs
#### Save .png of charts

In [ ]:

YoY_Total_Intake_Combined.plot(kind='bar', figsize=(20,25), subplots=5)

plt.title("Total Animal Intake during Holiday Season YoY (Daily)")
plt.xlabel("Date")
plt.ylabel("Total Intake")
plt.autoscale(enable=True, axis='both')

plt.tight_layout()
plt.savefig("../gitpug/Images/Total Intake YoY Bar (Daily).png", dpi=1020)

## Create Line chart to compare YoY data layered

#### use separate yearly dataframes to layer data
#### save .png of chart

In [ ]:
plt.figure(figsize=(35,8))
plt.tight_layout()
plt.plot(new13df['Date'], new13df['2013 intakes'],color='blue')
plt.plot(new14df['Date'], new14df['2014 intakes'],color='orange')
plt.plot(new15df['Date'], new15df['2015 intakes'], color='green')
plt.plot(new16df['Date'], new16df['2016 intakes'],color='red')
plt.plot(new17df['Date'], new17df['2017 intakes'],color='purple')
plt.legend()
plt.title("Animal intake during holiday season YoY")
plt.xlabel("Date")
plt.ylabel("Total animal intakes")
plt.xticks(YoY_Total_Intake_Combined['Date'], rotation=70, size='large')


plt.autoscale(enable=True, axis='both')
plt.savefig("../gitpug/Images/Total Intake YoY Line (Daily).png", dpi=1020, bbox_inches='tight')

## Break out Animal Type data to see if Higher intake rate of specific animal type collectively over holiday season

#### Create separate dataframes for each year to sum animal type counts

In [ ]:
DateTime_2013=q4df_2013["DateTime"]
AnimalType_2013=q4df_2013['Animal Type']

q4df_2013_2 = pd.DataFrame({'DateTime':DateTime_2013, 
                  'Animal Type':AnimalType_2013,
                  '2013 Counts':""})

q4df_2013_2=q4df_2013_2.groupby(["DateTime", 'Animal Type']).count()
q4df_2013_2=q4df_2013_2.groupby('Animal Type')
q4df_2013_2=q4df_2013_2.sum()
q4df_2013_2.head()


DateTime_2014=q4df_2014["DateTime"]
AnimalType_2014=q4df_2014['Animal Type']

q4df_2014_2 = pd.DataFrame({'DateTime':DateTime_2014, 
                  'Animal Type':AnimalType_2014,
                  '2014 Counts':""})

q4df_2014_2=q4df_2014_2.groupby(["DateTime", 'Animal Type']).count()
q4df_2014_2=q4df_2014_2.groupby('Animal Type')
q4df_2014_2=q4df_2014_2.sum()
q4df_2014_2.head()


DateTime_2015=q4df_2015["DateTime"]
AnimalType_2015=q4df_2015['Animal Type']

q4df_2015_2 = pd.DataFrame({'DateTime':DateTime_2015, 
                  'Animal Type':AnimalType_2015,
                  '2015 Counts':""})

q4df_2015_2=q4df_2015_2.groupby(["DateTime", 'Animal Type']).count()
q4df_2015_2=q4df_2015_2.groupby('Animal Type')
q4df_2015_2=q4df_2015_2.sum()
q4df_2015_2.head()


DateTime_2016=q4df_2016["DateTime"]
AnimalType_2016=q4df_2016['Animal Type']

q4df_2016_2 = pd.DataFrame({'DateTime':DateTime_2016, 
                  'Animal Type':AnimalType_2016,
                  '2016 Counts':""})

q4df_2016_2=q4df_2016_2.groupby(["DateTime", 'Animal Type']).count()
q4df_2016_2=q4df_2016_2.groupby('Animal Type')
q4df_2016_2=q4df_2016_2.sum()
q4df_2016_2.head()

DateTime_2017=q4df_2017["DateTime"]
AnimalType_2017=q4df_2017['Animal Type']

q4df_2017_2 = pd.DataFrame({'DateTime':DateTime_2017, 
                  'Animal Type':AnimalType_2017,
                  '2017 Counts':""})

q4df_2017_2=q4df_2017_2.groupby(["DateTime", 'Animal Type']).count()
q4df_2017_2=q4df_2017_2.groupby('Animal Type')
q4df_2017_2=q4df_2017_2.sum()
q4df_2017_2.head()

## Merge Animal Type YoY counts to single dataframe based on Animal Type

In [ ]:
Animal_Intake_Type_Combined=pd.merge(q4df_2013_2, q4df_2014_2, on="Animal Type")
Animal_Intake_Type_Combined=pd.merge(Animal_Intake_Type_Combined, q4df_2015_2, on="Animal Type")
Animal_Intake_Type_Combined=pd.merge(Animal_Intake_Type_Combined, q4df_2016_2, on="Animal Type")
Animal_Intake_Type_Combined=pd.merge(Animal_Intake_Type_Combined, q4df_2017_2, on="Animal Type")

Animal_Intake_Type_Combined.head()

## Create YoY Bar chart comparison for animal types and total intake over season

#### save .png of chart

In [ ]:
Animal_Intake_Type_Combined.plot(kind='bar', figsize=(15,5), title='Animal intake by animal type over holiday season (11/21-1/8 YoY)', 
                fontsize= 15 )

plt.xlabel("Animal Type")
plt.ylabel("Total Intake")

plt.autoscale(enable=True, axis='both')
plt.savefig("../gitpug/Images/Total Intake by Animal Type Bar.png", dpi=1020, bbox_inches='tight')